repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [ --fix=no ]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [ --allow-multiple-documents ]
        exclude: |
          (?x)^(
              charts/pvc-exporter/templates/.+.yaml
          )$
      - id: check-json
      - id: check-toml
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: helmlint
      # - id: yapf
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: '2.4.0'
    hooks:
      - id: editorconfig-checker
        alias: ec
        exclude: |
          (?x)^(
              LICENSE|
              COPYING|
              charts/pvc-exporter/templates/.+.yaml
          )$
  - repo: https://github.com/hadolint/hadolint
    rev: v2.8.0
    hooks:
      - id: hadolint
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.8.2
    hooks:
      - id: check-github-workflows
