apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: block-pvc-scanner
  namespace: pvc-exporter
  labels:
    app: pvc-exporter
    com: block-pvc-scanner
spec:
  selector:
    matchLabels:
      com: block-pvc-scanner
      app: pvc-exporter
  template:
    metadata:
      labels:
        com: block-pvc-scanner
        app: pvc-exporter
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: block-pvc-scanner
        image: dockerid31415926/block-pvc-scanner
        ports:
        - containerPort: 8848
          name: metrics
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: root-path
          mountPath: /host
          readOnly: true
      volumes:
      - name: root-path
        hostPath:
          path: /
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pvc-exporter
    com: block-pvc-scanner
  name: block-pvc-scanner
  namespace: pvc-exporter
spec:
  ports:
  - port: 8848
    name: metrics
    protocol: TCP
    targetPort: 8848
  selector:
    app: pvc-exporter
    com: block-pvc-scanner
  type: NodePort
