apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-pvc-mapping
  namespace: pvc-exporter
  labels:
    app: pvc-exporter
    com: pod-pvc-mapping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-exporter
      com: pod-pvc-mapping
  template:
    metadata:
      labels:
        app: pvc-exporter
        com: pod-pvc-mapping
    spec:
      containers:
      - name: pod-pvc-mapping
        image: dockerid31415926/pod-pvc-mapping
        ports:
        - containerPort: 8849
          name: metrics
      serviceAccountName: pvc-exporter-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pvc-exporter
    com: pod-pvc-mapping
  name: pod-pvc-mapping
  namespace: pvc-exporter
spec:
  ports:
  - port: 8849
    name: metrics
    protocol: TCP
    targetPort: 8849
  selector:
    app: pvc-exporter
    com: pod-pvc-mapping
  type: NodePort
