{{- $fullName := include "pvc-exporter.fullname" . -}}
{{- if .Values.BlockPvcScanner.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: {{ $fullName }}
    {{- with .Values.BlockPvcScanner.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.BlockPvcScanner.podMonitor.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $fullName }}
  namespace: {{.Values.namespace}}
spec:
  jobLabel: app
  selector:
    matchLabels:
      com: {{ $fullName }}-block-pvc-scanner
  podMetricsEndpoints:
    - port: metrics
      scheme: http
      path: /
      interval: 30s
  {{- end }}
