{{- $fullName := include "pvc-exporter.fullname" . -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $fullName }}-block-pvc-scanner
  namespace: {{.Values.namespace}}
  labels:
    app: {{ $fullName }}
    com: {{ $fullName }}-block-pvc-scanner
    {{- with .Values.BlockPvcScanner.daemonSet.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.BlockPvcScanner.daemonSet.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ $fullName }}
      com: {{ $fullName }}-block-pvc-scanner
  template:
    metadata:
      labels:
        app: {{ $fullName }}
        com: {{ $fullName }}-block-pvc-scanner
        {{- with .Values.BlockPvcScanner.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.BlockPvcScanner.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.BlockPvcScanner.image.pullSecrets | nindent 8 }}
      {{- with .Values.BlockPvcScanner.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.BlockPvcScanner.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: block-pvc-scanner
        {{- with .Values.BlockPvcScanner.image }}
        image: "{{ .repository }}{{ if .digest }}@{{ .digest }}{{ else }}:{{ .tag | default $.Chart.AppVersion }}{{ end }}"
        imagePullPolicy: {{ .pullPolicy }}
        {{- end }}
        ports:
        - containerPort: {{.Values.BlockPvcScanner.containerPort}}
          name: metrics
          protocol: TCP
        {{- with .Values.BlockPvcScanner.resources }}
        resources:
        {{- toYaml . | nindent 12 }}
        {{- end }}
        volumeMounts:
        - name: root-path
          mountPath: /host
          readOnly: true
        - name: host-kubelet
          mountPath: /var/lib/kubelet
          readOnly: true
        {{- with .Values.BlockPvcScanner.livenessProbe }}
        livenessProbe:
        {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.BlockPvcScanner.securityContext }}
        securityContext:
        {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.BlockPvcScanner.env }}
        env:
      {{- toYaml . | nindent 10 }}
      {{- end }}
      volumes:
      - name: root-path
        hostPath:
          path: /
      - name: host-kubelet
        hostPath:
          path: /var/lib/kubelet
