{{- $fullName := include "pvc-exporter.fullname" . -}}
  {{- if .Values.BlockPvcScanner.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ $fullName }}
  {{- with .Values.BlockPvcScanner.serviceMonitor.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.BlockPvcScanner.serviceMonitor.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace | default .Values.namespace }}
spec:
  selector:
    matchLabels:
      com: {{ $fullName }}-block-pvc-scanner
  endpoints:
    - interval: 30s
      targetPort: metrics
      scheme: http
      path: /
      port: metrics
  jobLabel: app
  {{- end }}
