{{- if or (kindIs "invalid" .Values.createNamespace) (.Values.createNamespace) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  {{- with .Values.namespaceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.namespaceLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
