{{- $fullName := include "pvc-exporter.fullname" . -}}
{{- if .Values.PodPvcMapping.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ $fullName }}
    {{- with .Values.PodPvcMapping.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.PodPvcMapping.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $fullName }}
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      com: {{ $fullName }}-pod-pvc-mapping
  endpoints:
  - interval: 30s
    targetPort: metrics
    scheme: http
    path: /
    port: metrics
  jobLabel: app
{{- end}}
