{{- $fullName := include "pvc-exporter.fullname" . -}}
  {{- if .Values.PodPvcMapping.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: {{ $fullName }}
  {{- with .Values.PodPvcMapping.podMonitor.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.PodPvcMapping.podMonitor.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace | default .Values.namespace }}
spec:
  jobLabel: app
  selector:
    matchLabels:
      com: {{ $fullName }}-pod-pvc-mapping
  podMetricsEndpoints:
    - port: metrics
      scheme: http
      path: /
      interval: 30s
  {{- end }}
