{{- $fullName := include "pvc-exporter.fullname" . -}}
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ $fullName }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $fullName }}
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: {{ $fullName }}
  endpoints:
  - interval: 30s
    targetPort: metrics
    scheme: http
    path: /
  jobLabel: app
{{- end}}
