{{- $fullName := include "pvc-exporter.fullname" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $fullName }}-cr
  {{- with .Values.clusterRole.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.clusterRole.labels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
- nonResourceURLs:
  - '*'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullName }}-crbinding
  {{- with .Values.clusterRoleBinding.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.clusterRoleBinding.labels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $fullName }}-cr
subjects:
- kind: ServiceAccount
  name: {{ $fullName }}-sa
  namespace: {{ .Release.Namespace | default .Values.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}-sa
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.labels }}
  labels:
  {{- toYaml . | nindent 4 }}
  {{- end }}
