# Default values for pvc-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: pvc-exporter
createNamespace: true
namespaceLabels: {}
namespaceAnnotations: {}

PodPvcMapping:
  image:
    repository: balihb/pod-pvc-mapping
    tag: ""
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  replicaCount: 1

  containerPort: 8849
  service:
    enabled: true
    headless: false
    ## If PodPvcMapping.service.headless=true, then ignore type
    type: NodePort
    port: 8849
    labels: {}
    annotations: {}
    # prometheus.io/path: "/"
    # prometheus.io/port: "8849"
    # prometheus.io/scrape: "true"

  env:
  # - name: APP_HTTP_SERVER_PORT
  #  value: "8849"
  # - name: APP_LOG_FORMAT
  #   value: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  # - name: APP_LOG_LEVEL
  #   value: "DEBUG"

  nodeSelector: {}
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule

  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi

  livenessProbe:
    httpGet:
      path: /
      port: metrics
    timeoutSeconds: 3
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true

  deployment:
    labels: {}
    annotations: {}

  pod:
    labels: {}
    annotations: {}

  podMonitor:
    enabled: false
    labels: {}
    annotations: {}

  serviceMonitor:
    enabled: true
    labels: {}
    annotations: {}

BlockPvcScanner:
  enabled: true

  image:
    repository: balihb/block-pvc-scanner
    tag: ""
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  containerPort: 8848
  service:
    enabled: false
    headless: false
    ## If BlockPvcScanner.service.headless=true, then ignore type
    type: NodePort
    port: 8848
    labels: {}
    annotations: {}
    # prometheus.io/path: "/"
    # prometheus.io/port: "8848"
    # prometheus.io/scrape: "true"

  env: []
  # - name: APP_HTTP_SERVER_PORT
  #  value: "8849"
  # - name: APP_LOG_FORMAT
  #   value: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  # - name: APP_LOG_LEVEL
  #   value: "DEBUG"

  nodeSelector: {}
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule

  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi

  livenessProbe:
    httpGet:
      path: /
      port: metrics
    timeoutSeconds: 3
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true

  daemonSet:
    labels: {}
    annotations: {}

  pod:
    labels: {}
    annotations: {}

  podMonitor:
    enabled: true
    labels: {}
    annotations: {}

  serviceMonitor:
    enabled: false
    labels: {}
    annotations: {}

clusterRole:
  labels: {}
  annotations: {}

clusterRoleBinding:
  labels: {}
  annotations: {}

serviceAccount:
  labels: {}
  annotations: {}

defaultDashboard:
  enabled: false
  uid: 7YOYYp-Mz
  title: 'PVC Usage'
  labels: {}
  annotations: {}
