from kubernetes.client import V1PersistentVolumeClaim, V1Pod, V1Namespace, V1ObjectMeta, V1PodSpec, V1Volume, \
    V1PersistentVolumeClaimVolumeSource, V1PersistentVolumeClaimSpec, V1Container

from .helper import TstKubeClientImpl

just_one = TstKubeClientImpl(
    nss=[
        V1Namespace(
            metadata=V1ObjectMeta(
                name='tst_ns_1'
            )
        )
    ],
    pods=[
        V1Pod(
            metadata=V1ObjectMeta(
                name='tst_pod_1',
                namespace='tst_ns_1'
            ),
            spec=V1PodSpec(
                containers=[
                    V1Container(
                        name='tst_pod_1_cnt'
                    )
                ],
                volumes=[
                    V1Volume(
                        name='tst_vol',
                        persistent_volume_claim=V1PersistentVolumeClaimVolumeSource(
                            claim_name='tst_claim_1'
                        )
                    )
                ]
            )
        )
    ],
    pvcs=[
        V1PersistentVolumeClaim(
            metadata=V1ObjectMeta(
                name='tst_claim_1',
                namespace='tst_ns_1'
            ),
            spec=V1PersistentVolumeClaimSpec(
                volume_name='pvc-2f0c4198-821b-4629-ab8f-59a993e3cd00'
            )
        )
    ]
)

empty_env = TstKubeClientImpl(
    nss=[],
    pods=[],
    pvcs=[]
)

different_namespace = TstKubeClientImpl(
    nss=[
        V1Namespace(
            metadata=V1ObjectMeta(
                name='tst_ns_1'
            )
        ),
        V1Namespace(
            metadata=V1ObjectMeta(
                name='tst_ns_2'
            )
        )
    ],
    pods=[
        V1Pod(
            metadata=V1ObjectMeta(
                name='tst_pod_1',
                namespace='tst_ns_1'
            ),
            spec=V1PodSpec(
                containers=[
                    V1Container(
                        name='tst_pod_1_cnt'
                    )
                ],
                volumes=[
                    V1Volume(
                        name='tst_vol',
                        persistent_volume_claim=V1PersistentVolumeClaimVolumeSource(
                            claim_name='tst_claim_1'
                        )
                    )
                ]
            )
        ),
        V1Pod(
            metadata=V1ObjectMeta(
                name='tst_pod_1',
                namespace='tst_ns_2'
            ),
            spec=V1PodSpec(
                containers=[
                    V1Container(
                        name='tst_pod_1_cnt'
                    )
                ],
                volumes=[
                    V1Volume(
                        name='tst_vol',
                        persistent_volume_claim=V1PersistentVolumeClaimVolumeSource(
                            claim_name='tst_claim_1'
                        )
                    )
                ]
            )
        )
    ],
    pvcs=[
        V1PersistentVolumeClaim(
            metadata=V1ObjectMeta(
                name='tst_claim_1',
                namespace='tst_ns_1'
            ),
            spec=V1PersistentVolumeClaimSpec(
                volume_name='pvc-9f2c31f4-e31c-459f-bdb4-08b0ba086644'
            )
        ),
        V1PersistentVolumeClaim(
            metadata=V1ObjectMeta(
                name='tst_claim_1',
                namespace='tst_ns_2'
            ),
            spec=V1PersistentVolumeClaimSpec(
                volume_name='pvc-40416cb8-37fb-4c27-ad06-e4f1d851b740'
            )
        )
    ]
)

two_vol_same_ns = TstKubeClientImpl(
    nss=[
        V1Namespace(
            metadata=V1ObjectMeta(
                name='tst_ns_1'
            )
        )
    ],
    pods=[
        V1Pod(
            metadata=V1ObjectMeta(
                name='tst_pod_1',
                namespace='tst_ns_1'
            ),
            spec=V1PodSpec(
                containers=[
                    V1Container(
                        name='tst_pod_1_cnt'
                    )
                ],
                volumes=[
                    V1Volume(
                        name='tst_vol',
                        persistent_volume_claim=V1PersistentVolumeClaimVolumeSource(
                            claim_name='tst_claim_1'
                        )
                    )
                ]
            )
        ),
        V1Pod(
            metadata=V1ObjectMeta(
                name='tst_pod_1',
                namespace='tst_ns_1'
            ),
            spec=V1PodSpec(
                containers=[
                    V1Container(
                        name='tst_pod_1_cnt'
                    )
                ],
                volumes=[
                    V1Volume(
                        name='tst_vol',
                        persistent_volume_claim=V1PersistentVolumeClaimVolumeSource(
                            claim_name='tst_claim_2'
                        )
                    )
                ]
            )
        )
    ],
    pvcs=[
        V1PersistentVolumeClaim(
            metadata=V1ObjectMeta(
                name='tst_claim_1',
                namespace='tst_ns_1'
            ),
            spec=V1PersistentVolumeClaimSpec(
                volume_name='pvc-9f2c31f4-e31c-459f-bdb4-08b0ba086644'
            )
        ),
        V1PersistentVolumeClaim(
            metadata=V1ObjectMeta(
                name='tst_claim_2',
                namespace='tst_ns_1'
            ),
            spec=V1PersistentVolumeClaimSpec(
                volume_name='pvc-40416cb8-37fb-4c27-ad06-e4f1d851b740'
            )
        )
    ]
)

two_vol_same_ns_vol_removed = TstKubeClientImpl(
    nss=[
        V1Namespace(
            metadata=V1ObjectMeta(
                name='tst_ns_1'
            )
        )
    ],
    pods=[
        V1Pod(
            metadata=V1ObjectMeta(
                name='tst_pod_1',
                namespace='tst_ns_1'
            ),
            spec=V1PodSpec(
                containers=[
                    V1Container(
                        name='tst_pod_1_cnt'
                    )
                ],
                volumes=[
                    V1Volume(
                        name='tst_vol',
                        persistent_volume_claim=V1PersistentVolumeClaimVolumeSource(
                            claim_name='tst_claim_1'
                        )
                    )
                ]
            )
        ),
        V1Pod(
            metadata=V1ObjectMeta(
                name='tst_pod_1',
                namespace='tst_ns_1'
            ),
            spec=V1PodSpec(
                containers=[
                    V1Container(
                        name='tst_pod_1_cnt'
                    )
                ]
            )
        )
    ],
    pvcs=[
        V1PersistentVolumeClaim(
            metadata=V1ObjectMeta(
                name='tst_claim_1',
                namespace='tst_ns_1'
            ),
            spec=V1PersistentVolumeClaimSpec(
                volume_name='pvc-9f2c31f4-e31c-459f-bdb4-08b0ba086644'
            )
        )
    ]
)
