name: release
on:
  push:
    branches:
      - omaster
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
      - uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: 5.7.0
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10
        with:
          useConfigFile: true

      - name: Sonar cache
        id: cache-sonar
        uses: actions/cache@v2
        with:
          path: /opt/sonar-scanner/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectVersion=${{ steps.gitversion.outputs.semVer }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: VERSION file block-pvc-scanner
        run: |
          echo "${{ steps.gitversion.outputs.semVer }}" > block_pvc_scanner/src/block_pvc_scanner/VERSION
      - name: VERSION file pod-pvc-mapping
        run: |
          echo "${{ steps.gitversion.outputs.semVer }}" > pod_pvc_mapping/src/pod_pvc_mapping/VERSION
      - name: build deps
        run: |
          python3 -m pip install --upgrade build
      - name: build Python package block-pvc-scanner
        run: |
          cd block_pvc_scanner
          python3 -m build --sdist
      - name: build Python package pod-pvc-mapping
        run: |
          cd pod_pvc_mapping
          python3 -m build --sdist

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker build and push block-pvc-scanner
        id: docker_build_block_pvc_scanner
        uses: docker/build-push-action@v2
        with:
          context: ./block_pvc_scanner
          file: ./block_pvc_scanner/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/block-pvc-scanner:${{ steps.gitversion.outputs.semVer }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/block-pvc-scanner:latest
            ghcr.io/${{ github.repository_owner }}/block-pvc-scanner:${{ steps.gitversion.outputs.semVer }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Docker build and push pod-pvc-mapping
        id: docker_build_pod_pvc_mapping
        uses: docker/build-push-action@v2
        with:
          context: ./pod_pvc_mapping
          file: ./pod_pvc_mapping/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/pod-pvc-mapping:${{ steps.gitversion.outputs.semVer }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/pod-pvc-mapping:latest
            ghcr.io/${{ github.repository_owner }}/pod-pvc-mapping:${{ steps.gitversion.outputs.semVer }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Update chart version in the related HelmChart Charts.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'charts/pvc-exporter/Chart.yaml'
          propertyPath: 'version'
          value: ${{ steps.gitversion.outputs.semVer }}
          createPR: false
          commitChange: false
          updateFile: true
          message: 'Update chart version to ${{ steps.image.outputs.version }}'
      - name: Update appVersion in the related HelmChart Charts.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'charts/pvc-exporter/Chart.yaml'
          propertyPath: 'appVersion'
          value: "${{ steps.gitversion.outputs.semVer }}"
          createPR: false
          commitChange: false
          updateFile: true
          message: 'Update appVersion to ${{ steps.image.outputs.version }}'

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "block_pvc_scanner/dist/*.tar.gz,pod_pvc_mapping/dist/*.tar.gz"
          tag: ${{ steps.gitversion.outputs.semVer }}
          commit: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: azure/setup-helm@v1
        with:
          version: v3.6.3

      - uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
